 services:
  - type: web
    name: n8n-v2
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_SECURE_COOKIE
        value: "false"
#  ⬆️  Notice: NO DB_* vars and NO `databases:` section.
#  n8n will boot with its default SQLite so the service can come up.

      


 
 
