services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_SECURE_COOKIE
        value: "false"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_SCHEMA
        value: "public"
      - key: DB_POSTGRESDB_SSL
        value: "false"

databases:
  - name: n8n-postgres
    plan: free
 
