 services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 5
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n.onrender.com/
      - key: VUE_APP_URL_BASE_API
        value: https://n8n.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: America/Edmonton
      - key: AUTO_IMPORT_WORKFLOWS
        value: "true"
      - key: IMPORT_OVERWRITE
        value: "false"
      - key: EXECUTIONS_MODE
        value: regular
